---
- name: Install Jenkins and Docker on Amazon Linux
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Java 
      yum:
        name: java-17
        state: present
      

    - name: Add Jenkins Repository
      yum_repository:
        name: jenkins
        description: Jenkins Official Repository
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgcheck: no   # Disabling GPG check for Jenkins
        state: present
      when: "'CI/CD-server' in group_names"  # Only add Jenkins repository on 'CI/CD-server' hosts

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
      when: "'CI/CD-server' in group_names"  # Only install Jenkins on 'CI/CD-server' hosts

    - name: Start Jenkins Service
      service:
        name: jenkins
        state: started
        enabled: yes
      when: "'CI/CD-server' in group_names"  # Only start Jenkins service on 'CI/CD-server' hosts
