---
- name: Install Jenkins on Amazon Linux
  hosts: all
  become: true
  tasks:
    - name: Install Java (required for Jenkins)
      yum:
        name: java-17
        state: present

    - name: Add Jenkins Repository
      yum_repository:
        name: jenkins
        description: Jenkins Official Repository
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgcheck: no   # Disabling GPG check for Jenkins
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins Service
      service:
        name: jenkins
        state: started
        enabled: yes
